Repository zeropsio/docs, pull requests merged in 2024-12, with the labels that each got.

#107 Draft: Yaml Preprocessor
  apps/docs/content/dotnet/how-to/build-pipeline.mdx
  apps/docs/content/dotnet/how-to/create.mdx
  apps/docs/content/dotnet/how-to/env-variables.mdx
  apps/docs/content/dotnet/how-to/scaling.mdx
  apps/docs/content/elasticsearch/how-to/create.mdx
  apps/docs/content/go/how-to/build-pipeline.mdx
  apps/docs/content/go/how-to/create.mdx
  apps/docs/content/go/how-to/env-variables.mdx
  apps/docs/content/go/how-to/scaling.mdx
  apps/docs/content/java/how-to/build-pipeline.mdx
  apps/docs/content/java/how-to/create.mdx
  apps/docs/content/java/how-to/env-variables.mdx
  apps/docs/content/java/how-to/scaling.mdx
  apps/docs/content/keydb/how-to/create.mdx
  apps/docs/content/keydb/how-to/scale.mdx
  apps/docs/content/mariadb/how-to/create.mdx
  apps/docs/content/nginx/how-to/build-pipeline.mdx
  apps/docs/content/nginx/how-to/create.mdx
  apps/docs/content/nginx/how-to/env-variables.mdx
  apps/docs/content/nginx/how-to/scaling.mdx
  apps/docs/content/nodejs/how-to/build-pipeline.mdx
  apps/docs/content/nodejs/how-to/create.mdx
  apps/docs/content/nodejs/how-to/env-variables.mdx
  apps/docs/content/nodejs/how-to/scaling.mdx
  apps/docs/content/object-storage/how-to/create.mdx
  apps/docs/content/php/how-to/build-pipeline.mdx
  apps/docs/content/php/how-to/create.mdx
  apps/docs/content/php/how-to/env-variables.mdx
  apps/docs/content/php/how-to/scaling.mdx
  apps/docs/content/postgresql/how-to/create.mdx
  apps/docs/content/python/how-to/build-pipeline.mdx
  apps/docs/content/python/how-to/create.mdx
  apps/docs/content/python/how-to/env-variables.mdx
  apps/docs/content/python/how-to/scaling.mdx
  apps/docs/content/rabbitmq/how-to/create.mdx
  apps/docs/content/references/import.mdx
  apps/docs/content/references/importyml/pre-processor.mdx
  apps/docs/content/references/importyml/type-list.mdx
  apps/docs/content/references/zeropsyml.mdx
  apps/docs/content/rust/how-to/build-pipeline.mdx
  apps/docs/content/rust/how-to/create.mdx
  apps/docs/content/rust/how-to/env-variables.mdx
  apps/docs/content/rust/how-to/scaling.mdx
  apps/docs/sidebars.js
  apps/docs/src/components/Dropdown/index.tsx
  apps/docs/src/css/_docusaurus.css
  apps/docs/src/theme/CodeBlock/index.tsx
  packages/tailwind/base.tailwind.config.js
Labels: 🌱 Review me

#111 previous and next buttons
  apps/docs/src/components/GroupCards/index.tsx
  apps/docs/src/components/NavigationButons/index.tsx
  apps/docs/src/theme/DocItem/Layout/index.tsx
Labels: 🌱 Review me

#92 feat(features): add a pricing page & calculator
  apps/docs/content/features/pricing.mdx
  apps/docs/sidebars.js
  apps/docs/src/components/PricingCalculator/calculator.css
  apps/docs/src/components/PricingCalculator/index.tsx
Labels: ✨ Improve me

#96 Fix #95
  apps/docs/content/dotnet/how-to/build-pipeline.mdx
  apps/docs/content/dotnet/how-to/build-process.mdx
  apps/docs/content/dotnet/how-to/customize-runtime.mdx
  apps/docs/content/dotnet/how-to/logs.mdx
  apps/docs/content/features/infrastructure.mdx
  apps/docs/content/go/how-to/build-pipeline.mdx
  apps/docs/content/go/how-to/build-process.mdx
  apps/docs/content/go/how-to/customize-runtime.mdx
  apps/docs/content/go/how-to/logs.mdx
  apps/docs/content/java/how-to/build-pipeline.mdx
  apps/docs/content/java/how-to/build-process.mdx
  apps/docs/content/java/how-to/customize-runtime.mdx
  apps/docs/content/java/how-to/logs.mdx
  apps/docs/content/nginx/how-to/build-pipeline.mdx
  apps/docs/content/nginx/how-to/customize-runtime.mdx
  apps/docs/content/nginx/how-to/logs.mdx
  apps/docs/content/nodejs/how-to/build-pipeline.mdx
  apps/docs/content/nodejs/how-to/build-process.mdx
  apps/docs/content/nodejs/how-to/customize-runtime.mdx
  apps/docs/content/php/how-to/build-pipeline.mdx
  apps/docs/content/php/how-to/build-process.mdx
  apps/docs/content/php/how-to/customize-runtime.mdx
  apps/docs/content/php/how-to/logs.mdx
  apps/docs/content/python/how-to/build-pipeline.mdx
  apps/docs/content/python/how-to/build-process.mdx
  apps/docs/content/python/how-to/customize-runtime.mdx
  apps/docs/content/python/how-to/logs.mdx
  apps/docs/content/rust/how-to/build-pipeline.mdx
  apps/docs/content/rust/how-to/build-process.mdx
  apps/docs/content/rust/how-to/customize-runtime.mdx
  apps/docs/content/rust/how-to/logs.mdx
  apps/docs/sidebars.js
Labels: 🌱 Review me

#114 zCLI Flags Improvement
  apps/docs/content/references/cli/commands.mdx
Labels: 🌱 Review me

#106 chore: added example with php.ini values in env variables
  apps/docs/content/php/how-to/customize-runtime.mdx
Labels: 🌱 Review me

#103 chore: complete object storage overview
  apps/docs/content/object-storage/how-to/create.mdx
  apps/docs/content/object-storage/overview.mdx
Labels: 🌱 Review me

#108 feat: new cron page
  apps/docs/content/bun/how-to/build-pipeline.mdx
  apps/docs/content/deno/how-to/build-pipeline.mdx
  apps/docs/content/dotnet/how-to/build-pipeline.mdx
  apps/docs/content/elixir/how-to/build-pipeline.mdx
  apps/docs/content/gleam/how-to/build-pipeline.mdx
  apps/docs/content/go/how-to/build-pipeline.mdx
  apps/docs/content/java/how-to/build-pipeline.mdx
  apps/docs/content/nodejs/how-to/build-pipeline.mdx
  apps/docs/content/php/how-to/build-pipeline.mdx
  apps/docs/content/python/how-to/build-pipeline.mdx
  apps/docs/content/rust/how-to/build-pipeline.mdx
  apps/docs/content/zerops-yml/base-list.mdx
  apps/docs/content/zerops-yml/cron.mdx
  apps/docs/content/zerops-yml/specification.mdx
  apps/docs/sidebars.js
  apps/docs/src/theme/Icon/index.tsx
Labels: 🌱 Review me

#121 chore: add nginx service prerender.io support
  apps/docs/content/nginx/faq.mdx
  apps/docs/content/nginx/how-to/customize-web-server.mdx
  apps/docs/content/nginx/how-to/env-variables.mdx
  apps/docs/content/nginx/overview.mdx
Labels: 🌱 Review me

#127 z0 - elasticsearch - basic configuration
  apps/docs/content/elasticsearch/how-to/connect.mdx
  apps/docs/content/elasticsearch/how-to/control.mdx
  apps/docs/content/elasticsearch/how-to/create.mdx
  apps/docs/content/elasticsearch/how-to/delete.mdx
  apps/docs/content/elasticsearch/how-to/export-import-data.mdx
  apps/docs/content/elasticsearch/how-to/manage.mdx
  apps/docs/content/elasticsearch/how-to/scale.mdx
  apps/docs/content/elasticsearch/overview.mdx
  apps/docs/content/elasticsearch/reference/cli.mdx
  apps/docs/content/elasticsearch/reference/import.mdx
  apps/docs/content/homepage.mdx
  apps/docs/sidebars.js
Labels: 🌱 Review me

#112 Zsc page
  apps/docs/content/references/gitlab-integration.mdx
  apps/docs/content/references/zsc.mdx
  apps/docs/docusaurus.config.js
  apps/docs/sidebars.js
  apps/docs/static/favicon.ico
  apps/docs/static/img/gui/zsc-web-terminal.webp
Labels: 🌱 Review me

#134 `/discord` redirect link
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  apps/docs/content/help/faq.mdx
  apps/docs/docusaurus.config.js
  apps/docs/src/pages/discord.js
Labels: 🌱 Review me

#132 Add Github Workflow Section to /github-integration
  apps/docs/content/references/github-integration.mdx
Labels: 🌱 Review me

#139 Elasticsearch backup and generic backup page
  apps/docs/content/elasticsearch/overview.mdx
  apps/docs/content/features/backup.mdx
  apps/docs/sidebars.js
Labels: ♻️ Changes Requested
